### ISSUE TITLE
invalid key

### ISSUE THREAD

**Issue by lifenglsf** [iofeqkurrc42/jetbra-server#2]
下载了项目本地运行，然后输入active code提示invalid key，是ja-filter的配置文件没有跟上吗，ja-filter的配置文件用的[这个大佬的](https://linux.do/t/topic/35142)

**Comment by iofeqkurrc42** [comment]
你看看这些:
- https://linux.do/t/topic/42328
- https://linux.do/t/topic/30480

**Comment by lifenglsf** [comment]
有时间我再研究下，应该是power.conf要换下

**Comment by iofeqkurrc42** [comment]
热佬之前回复了 issue,  文档我也更新一下, 你可以参考下
- https://github.com/novice88/jetbra-server-rust/issues/3
- https://linux.do/t/topic/1798
